# Generated by Django 3.2.5 on 2021-08-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit_submission',
            name='submission_subreddit',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
